config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :musics
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "static_pages#index"
  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'Adicionar músicas', to: 'musics#new'
  get 'Adicionar músicas', to: 'musics#new'
  get 'criar usuario', to: 'user#new'
  get 'criar playlist', to: 'playlist#new'
  post 'https://api.spotify.com/v1/users/{user_id}/playlists', to: 'playlists#new'

  #A serem desenvolvidos: (documentação spotify)
  #get 'Obter playlist', to: 'playlists/{playlist_id}'
  #post 'Adicionar músicas à playlist', to: 'playlists/{playlist_id}/tracks'
  #get 'Obter detalhes da playlist', to: 'playlists/{playlist_id}/tracks'
  #range_start, insert_before, range_length and snapshot_id
  #put 'atualizar playlist', to: 'playlists/{playlist_id}/tracks'
  #delete 'excluir músicas à playlist', to: 'playlists/{playlist_id}/tracks'

  #get 'sobre', to: 'static_pages#sobre'
  
  resources :users, only: [:new , :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/playlist.rb
class Playlist < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save :email_downcase

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }


  private
    def email_downcase
      self.email.downcase!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: %i[ show edit update destroy ]

  # GET /musics or /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1 or /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics or /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to music_url(@music), notice: "Music was successfully created." }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1 or /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to music_url(@music), notice: "Music was successfully updated." }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1 or /musics/1.json
  def destroy
    @music.destroy

    respond_to do |format|
      format.html { redirect_to musics_url, notice: "Music was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def music_params
      params.require(:music).permit(:name, :artist)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
        @titulo = "Gerenciador de Playlists"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_digest, :email, :cpf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
<footer>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path%>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  </nav>
</footer>
</nav>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-inverse navbar-static-top">

<div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Início', root_url, class: 'navbar-brand' %>
      </button>
      <%= link_to 'Cadastrar',new_user_path, class: 'navbar-brand' %>
      </button>
      <%= link_to 'Login', '#', class: 'navbar-brand' %>
      </button>
      <%= link_to 'Logar com Spotify', 'http://localhost:8888', class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="expanded-menu">
    

    </div>
</nav> 
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Projeto - Spotify </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music) do |form| %>
  <% if music.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% music.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/musics/_music.html.erb
<div id="<%= dom_id music %>">
  <p>
    <strong>Name:</strong>
    <%= music.name %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= music.artist %>
  </p>

</div>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render "form", music: @music %>

<br>

<div>
  <%= link_to "Show this music", @music %> |
  <%= link_to "Back to musics", musics_path %>
</div>

app/views/musics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Musics</h1>

<div id="musics">
  <% @musics.each do |music| %>
    <%= render music %>
    <p>
      <%= link_to "Show this music", music %>
    </p>
  <% end %>
</div>

<%= link_to "New music", new_music_path %>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render "form", music: @music %>

<br>

<div>
  <%= link_to "Back to musics", musics_path %>
</div>
<div>
  <%= link_to "Show musics", musics_path %>
</div>

app/views/musics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @music %>

<div>
  <%= link_to "Edit this music", edit_music_path(@music) %> |
  <%= link_to "Back to musics", musics_path %>

  <%= button_to "Destroy this music", @music, method: :delete %>
</div>

app/views/playlists/_busca.erb
https://api.spotify.com/v1/users/{user_id}/playlists

app/views/playlists/_form.html.erb
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <p>
    <strong>Name:</strong>
    <%= playlist.name %>
  </p>

</div>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Show this playlist", @playlist %> |
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Playlists</h1>

<div id="playlists">
  <% @playlists.each do |playlist| %>
    <%= render playlist %>
    <p>
      <%= link_to "Show this playlist", playlist %>
    </p>
  <% end %>
</div>

<%= link_to "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<h1> New playlist </h1>

<%= render "form", playlist: @playlist %> 

<%= render "busca", playlist: @playlist %>

<br>

<div>
  <%= link_to "Back to playlists", "#" %>
</div>

app/views/playlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @playlist %>

<div>
  <%= link_to "Edit this playlist", edit_playlist_path(@playlist) %> |
  <%= link_to "Back to playlists", playlists_path %>

  <%= button_to "Destroy this playlist", @playlist, method: :delete %>
</div>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
  Entre em contato com <a href="https://www.linkedin.com/in/rayane-qu%C3%A9zia-158620238/"> @rayquezia03 </a> para saber mais.
</p>

app/views/static_pages/index.html.erb
<h1> Olá, bem vindo!</h1>

<%= @titulo  %>



<div class="jumbotron">

  <h1>Projeto1</h1>
  <p>
    <%= link_to 'Criar Playlist', 'https://api.spotify.com/v1/users/{user_id}/playlists', class: 'btn btn-primary btn-lg' %>
  </p>

</div>  

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>
  Criando projeto para gerenciar Playlists colaborativas.
</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= user.cpf %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>